### ISSUE TITLE
Demo out of size

### ISSUE THREAD

**Issue by MadFra** [NeoSmartpen/Windows-SDK2.0#1]
The demo project have an issue in the size of form i tried to change the size but this doesn't solve the problem, the autosize is off.

**Comment by chyccs** [comment]
Hi MadFra,

Sorry for the late reply.

what's the meaning of autosize?
I think you can create any size of bitmap and picturebox control.
I want to know detailed information about this issue.

**Comment by MadFra** [comment]
Dear Hwa-Young Choi,

I'm developing a software for the recognition of the data received from the pen,

I need to convert the dot received similar to digital ink, do you have any suggestion

Thanks,

Francesco.

________________________________

**Comment by chyccs** [comment]
Hi MadFra,

What is the meaning of recognition of the data?
Does it mean handwriting recognition?
