### ISSUE TITLE
Sizing A4 and A3

### ISSUE THREAD

**Issue by Belisarith** [NeoSmartpen/Windows-SDK2.0#10]
I am struck when evaluation the stroke data.
In your DrawStoke function there is the following resizing:

      
```
//603 Ring Note Height  5.52  5.41 	63.46 	88.88 
                    int dx = (int)( ( 5.52 * mWidth ) / 63.46 );
                    int dy = (int)( ( 5.41 * mHeight ) / 88.88 );

                    Renderer.draw( mBitmap, stroke, (float)( mWidth / 63.46f ), (float)( mHeight / 88.88f ), -dx, -dy, 1, Color.FromArgb( 200, Color.Blue ) );
```

Could you explain where the numbers 5.52, 5.41, 63.46 and 88.88 come from?
What would be the correct numbers, if I want to resize to A4 or A3, respectively?

**Comment by Belisarith** [comment]
Okay, I got it. It's the mm of your page format by 2.37mm the raster size of the ncode coordinate system. Maybe, in this case a small explanation would be helpfull for the demo.

**Comment by chyccs** [comment]
Thanks for the comments. We already know that users have a hard time understanding this. The documentation described is there, but we are aware of the lack and are looking for ways to improve it. Stay tuned for future SDK updates.
