### ISSUE TITLE
license questions

### ISSUE THREAD

**Issue by otsl0110** [NeoSmartpen/Windows-SDK2.0#5]
I cannot follow official neo smart pen forum link shown bottom of the page. Does it require an user account? if so, how to register?

I would like to know business license terms and conditions in detail.

1. royalty for using sdk (ios, android and windows sdk.)
2. ncode sdk license and conditions. 
3. can I resale ticket to 3rd party?
4. can I resale development platform made from sdks?

your prompt reply is highly appreciated.

Yutaka Takahashi.

**Comment by NeolabConvergence** [comment]
Hello  Yutaka,

I have forwarded your message to our sales team.

Can you send me your e-mail address, so that sales manager can contact you?
My e-mail is sksmania@neolab.net

Thank you for contacting us first.
Kyoung-su

**Comment by Peppepicciano** [comment]
We're a little company interested to integrate in our software this technology.
Can we have a quote for a license to print some thousand of different sheets of paper?
We're really interested in. 
Please send all the questions about it at giuseppe@igroup.it
Regards
Giuseppe Picciano
