### ISSUE TITLE
Moleskine NWP-F70 doesn't register tilt/twist

### ISSUE THREAD

**Issue by vrsimjosh** [NeoSmartpen/Windows-SDK2.0#6]
Hello, my company recently purchased the new moleskine with the model NWP-F70. We were informed that it used protocol v2 which documentation says added tilt and twist functionality. Unfortunately, when using the WindowsSDK2.0 and running the Neosmartpen.Demo inside it seems like tilt and twist information is always 0.

1. Have we done anything wrong? Does this version not have tilt&twist? Or is it just not supported yet by the SDK?

2. Also, do you know if it is possible in anyway to modify the code to get distance as well for any version?

Thank you,
Josh Armour

**Comment by chyccs** [comment]
Hi vrsimjosh,

Thank for using our product.

I will answer your question below.

1. The tilt and twist have not yet been implemented in the pen.
We will implement it later and make it available.

2. What does distance mean?

**Comment by vrsimjosh** [comment]
When tilt and twist is made available, do you know if the pen that we have will then be able to use it? Or will we need to get a new pen.

By distance, I meant the distance from the pen tip to the paper when it could detect the paper. We would like to use the pens as a tool for measuring technique of something else.

**Comment by chyccs** [comment]
When tilt and twist is made available, you will be able to use the features through firmware updates.
It is impossible to measure the distance between paper and pen. It is flexible depending on the brightness.

**Comment by dinglid** [comment]
@chyccs  Hello, I have the similar problem here and wondering when will the tilt/twist data be available. Could you please tell me around what time will the firmware update arrive (approximate time is more than enough)? This really changes the user experiences and vital to my project.
Thank you and looking forward to your reply.

**Comment by chyccs** [comment]
Hi dinglid,
We are currently working on implementing tilt and twist. However, it is hard to judge the specific update date and time.
