### ISSUE TITLE
Question: Download data via USB

### ISSUE THREAD

**Issue by SteveOswald** [NeoSmartpen/Windows-SDK2.0#7]
Hi,

is it possible to download the data from the pen via USB or do you only offer Bluetooth for communication? I've got a project, where I have many pens and many PCs and it should be possible to download data from the pen, without pairing it with every PC.

Best regards,
Steve

**Comment by chyccs** [comment]
Hi Steve,

Sorry for the late reply.
We recommend that you receive data via the Bluetooth interface.
There is a risk of file system corruption when accessing data with USB.

Best regards,
Choi
