### ISSUE TITLE
USB sample?

### ISSUE THREAD

**Issue by AkosLukacs** [NeoSmartpen/Windows-SDK2.0#8]
Hi!

I have seen you uploaded a USB sample, and tried with an N2 (NWP-F121), but couldn't connect to it.
Skimming through the source code looks like it is looking for virtual COM ports. But the pen does not show up as a virtual COM port.
Could you provide some info about how to connect via USB?

Thanks!

**Comment by chyccs** [comment]
Hi AkosLukacs,

Thank for using our product.
The updated USB project was developed for the new NWP-F51.
As a result, the NWP-F121 SDK won't work.
If you want a USB connection with your NWP-F121, please talk to our sales team(_global1@neolab.net) first.

Thanks
Choi

**Comment by AkosLukacs** [comment]
Hi Choi!

Thanks for the clarification.
Already sent an email to that email address on 08.23. Could you ping your sales team whether they received my email?

Thanks!
